import os
import google_auth_oauthlib.flow
import googleapiclient.discovery
from googleapiclient.http import MediaFileUpload

# 1. SETUP
CLIENT_SECRETS_FILE = "client_secret.json"
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

# Point to the file inside the 'output' folder
FOLDER_NAME = "output"
FILE_NAME = "final_video_subtitled.mp4" # <--- Change this to your actual video name
VIDEO_PATH = os.path.join(FOLDER_NAME, FILE_NAME)

def upload():
    # Check if the folder and file actually exist first
    if not os.path.exists(VIDEO_PATH):
        print(f"❌ Error: Could not find '{FILE_NAME}' in the '{FOLDER_NAME}' folder.")
        print(f"Full path searched: {os.path.abspath(VIDEO_PATH)}")
        return

    # 2. LOG IN
    flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(
        CLIENT_SECRETS_FILE, SCOPES)
    credentials = flow.run_local_server(port=0)
    youtube = googleapiclient.discovery.build("youtube", "v3", credentials=credentials)

    # 3. VIDEO DATA
    body = {
        "snippet": {
            "title": "Tech Mage Shorts #Shorts",
            "description": "Magic meets technology. Generated by Tech Mage.",
            "categoryId": "28"
        },
        "status": {
            "privacyStatus": "public",
            "selfDeclaredMadeForKids": False
        }
    }

    # 4. START UPLOAD
    print(f"🚀 Uploading from folder: {VIDEO_PATH}...")
    insert_request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=MediaFileUpload(VIDEO_PATH, chunksize=-1, resumable=True)
    )
    
    response = insert_request.execute()
    print(f"✅ DONE! Video ID: {response['id']}")
    print(f"Check it here: https://youtu.be/{response['id']}")

if __name__ == "__main__":
    upload()